apiVersion: v1
kind: Service
metadata:
  name: {{ include "__CHART__.fullname" . }}
  labels:
{{ include "__CHART__.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "__CHART__.selectorLabels" . | nindent 4 }}
